export enum MouseButtons {
	LEFT = 'left',
	RIGHT = 'right',
	MIDDLE = 'middle',
}

/**
 * Chrome DevTools Device Emulation
 */
export enum Device {
	'blackberryPlayBook' = 'Blackberry PlayBook',
	'blackberryPlayBookLandscape' = 'Blackberry PlayBook landscape',
	'blackBerryZ30' = 'BlackBerry Z30',
	'blackBerryZ30Landscape' = 'BlackBerry Z30 landscape',
	'galaxyNote_3' = 'Galaxy Note 3',
	'galaxyNote_3Landscape' = 'Galaxy Note 3 landscape',
	'galaxyNoteIi' = 'Galaxy Note II',
	'galaxyNoteIiLandscape' = 'Galaxy Note II landscape',
	'galaxySIii' = 'Galaxy S III',
	'galaxySIiiLandscape' = 'Galaxy S III landscape',
	'galaxyS5' = 'Galaxy S5',
	'galaxyS5Landscape' = 'Galaxy S5 landscape',
	'iPad' = 'iPad',
	'iPadLandscape' = 'iPad landscape',
	'iPadMini' = 'iPad Mini',
	'iPadMiniLandscape' = 'iPad Mini landscape',
	'iPadPro' = 'iPad Pro',
	'iPadProLandscape' = 'iPad Pro landscape',
	'iPhone4' = 'iPhone 4',
	'iPhone4Landscape' = 'iPhone 4 landscape',
	'iPhone5' = 'iPhone 5',
	'iPhone5Landscape' = 'iPhone 5 landscape',
	'iPhone6' = 'iPhone 6',
	'iPhone6Landscape' = 'iPhone 6 landscape',
	'iPhone6Plus' = 'iPhone 6 Plus',
	'iPhone6PlusLandscape' = 'iPhone 6 Plus landscape',
	'iPhone7' = 'iPhone 7',
	'iPhone7Landscape' = 'iPhone 7 landscape',
	'iPhone7Plus' = 'iPhone 7 Plus',
	'iPhone7PlusLandscape' = 'iPhone 7 Plus landscape',
	'iPhone8' = 'iPhone 8',
	'iPhone8Landscape' = 'iPhone 8 landscape',
	'iPhone8Plus' = 'iPhone 8 Plus',
	'iPhone8PlusLandscape' = 'iPhone 8 Plus landscape',
	'iPhoneSE' = 'iPhone SE',
	'iPhoneSELandscape' = 'iPhone SE landscape',
	'iPhoneX' = 'iPhone X',
	'iPhoneXLandscape' = 'iPhone X landscape',
	'iPhoneXR' = 'iPhone XR',
	'iPhoneXRLandscape' = 'iPhone XR landscape',
	'kindleFireHdx' = 'Kindle Fire HDX',
	'kindleFireHdxLandscape' = 'Kindle Fire HDX landscape',
	'lgOptimusL70' = 'LG Optimus L70',
	'lgOptimusL70Landscape' = 'LG Optimus L70 landscape',
	'microsoftLumia550' = 'Microsoft Lumia 550',
	'microsoftLumia950' = 'Microsoft Lumia 950',
	'microsoftLumia950Landscape' = 'Microsoft Lumia 950 landscape',
	'nexus10' = 'Nexus 10',
	'nexus10Landscape' = 'Nexus 10 landscape',
	'nexus4' = 'Nexus 4',
	'nexus4Landscape' = 'Nexus 4 landscape',
	'nexus5' = 'Nexus 5',
	'nexus5Landscape' = 'Nexus 5 landscape',
	'nexus5X' = 'Nexus 5X',
	'nexus5XLandscape' = 'Nexus 5X landscape',
	'nexus6' = 'Nexus 6',
	'nexus6Landscape' = 'Nexus 6 landscape',
	'nexus6P' = 'Nexus 6P',
	'nexus6PLandscape' = 'Nexus 6P landscape',
	'nexus7' = 'Nexus 7',
	'nexus7Landscape' = 'Nexus 7 landscape',
	'nokiaLumia_520' = 'Nokia Lumia 520',
	'nokiaLumia_520Landscape' = 'Nokia Lumia 520 landscape',
	'nokiaN9' = 'Nokia N9',
	'nokiaN9Landscape' = 'Nokia N9 landscape',
	'pixel2' = 'Pixel 2',
	'pixel2Landscape' = 'Pixel 2 landscape',
	'pixel2XL' = 'Pixel 2 XL',
	'pixel2XLLanscape' = 'Pixel 2 XL landscape',
}

/**
 * Lists all available keyboard control keys which can be used when sending a key press combination.
 *
 * @export
 * @enum {number}
 */
export const Key = {
	NULL: null,
	CANCEL: 'Cancel', // ^break
	HELP: 'Help',
	BACK_SPACE: 'Backspace',
	TAB: 'Tab',
	CLEAR: 'Clear',
	RETURN: 'Enter',
	ENTER: 'Enter',
	SHIFT: 'ShiftLeft',
	CONTROL: 'ControlLeft',
	ALT: 'AltLeft',
	PAUSE: 'Pause',
	ESCAPE: 'Escape',
	SPACE: 'Space',
	PAGE_UP: 'PageUp',
	PAGE_DOWN: 'PageDown',
	END: 'End',
	HOME: 'Home',
	ARROW_LEFT: 'ArrowLeft',
	LEFT: 'ArrowLeft',
	ARROW_UP: 'ArrowUp',
	UP: 'ArrowUp',
	ARROW_RIGHT: 'ArrowRight',
	RIGHT: 'ArrowRight',
	ARROW_DOWN: 'ArrowDown',
	DOWN: 'ArrowDown',
	INSERT: 'Insert',
	DELETE: 'Delete',
	SEMICOLON: 'Semicolon',
	EQUALS: 'Equal',

	NUMPAD0: 'Numpad0',
	NUMPAD1: 'Numpad1',
	NUMPAD2: 'Numpad2',
	NUMPAD3: 'Numpad3',
	NUMPAD4: 'Numpad4',
	NUMPAD5: 'Numpad5',
	NUMPAD6: 'Numpad6',
	NUMPAD7: 'Numpad7',
	NUMPAD8: 'Numpad8',
	NUMPAD9: 'Numpad9',
	MULTIPLY: 'NumpadMultiply',
	ADD: 'NumpadAdd',
	SEPARATOR: null,
	SUBTRACT: 'NumpadSubtract',
	DECIMAL: 'NumpadDecimal',
	DIVIDE: 'NumpadDivide',

	F1: 'F1',
	F2: 'F2',
	F3: 'F3',
	F4: 'F4',
	F5: 'F5',
	F6: 'F6',
	F7: 'F7',
	F8: 'F8',
	F9: 'F9',
	F10: 'F10',
	F11: 'F11',
	F12: 'F12',

	COMMAND: 'MetaLeft',
	META: 'MetaLeft',
}

export const userAgents = {
	iphone:
		'Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B179 Safari/7534.48.3',
	ipod:
		'Mozilla/5.0 (iPod; CPU iPhone OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B176 Safari/7534.48.3',
	ipad:
		'Mozilla/5.0 (iPad; CPU OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B176 Safari/7534.48.3',
	safariOSX:
		'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/536.25 (KHTML, like Gecko) Version/6.0 Safari/536.25',
	safariWindows:
		'Mozilla/5.0 (Windows; Windows NT 6.1) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2',
	ie7: 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)',
	ie8: 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0)',
	ie9: 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
	chromeOSX:
		'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
	chromeWindows:
		'Mozilla/5.0 (Windows; Windows NT 6.1) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
	ffOSX: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:11.0) Gecko/20100101 Firefox/11.0',
	ffWindows: 'Mozilla/5.0 (Windows NT 6.1; rv:11.0) Gecko/20100101 Firefox/11.0',
	operaOSX: 'Opera/9.80 (Macintosh; Intel Mac OS X 10.7.4; U; en) Presto/2.10.229 Version/11.62',
	operaWindows: 'Opera/9.80 (Windows NT 6.1; U; en) Presto/2.10.229 Version/11.62',
	robot: 'I AM ROBOT',
}

export const KeyDefinitions = {
	Digit0: { keyCode: 48, code: 'Digit0', shiftKey: ')', key: '0' },
	Digit1: { keyCode: 49, code: 'Digit1', shiftKey: '!', key: '1' },
	Digit2: { keyCode: 50, code: 'Digit2', shiftKey: '@', key: '2' },
	Digit3: { keyCode: 51, code: 'Digit3', shiftKey: '#', key: '3' },
	Digit4: { keyCode: 52, code: 'Digit4', shiftKey: '$', key: '4' },
	Digit5: { keyCode: 53, code: 'Digit5', shiftKey: '%', key: '5' },
	Digit6: { keyCode: 54, code: 'Digit6', shiftKey: '^', key: '6' },
	Digit7: { keyCode: 55, code: 'Digit7', shiftKey: '&', key: '7' },
	Digit8: { keyCode: 56, code: 'Digit8', shiftKey: '*', key: '8' },
	Digit9: { keyCode: 57, code: 'Digit9', shiftKey: '(', key: '9' },
	KeyA: { keyCode: 65, code: 'KeyA', shiftKey: 'A', key: 'a' },
	KeyB: { keyCode: 66, code: 'KeyB', shiftKey: 'B', key: 'b' },
	KeyC: { keyCode: 67, code: 'KeyC', shiftKey: 'C', key: 'c' },
	KeyD: { keyCode: 68, code: 'KeyD', shiftKey: 'D', key: 'd' },
	KeyE: { keyCode: 69, code: 'KeyE', shiftKey: 'E', key: 'e' },
	KeyF: { keyCode: 70, code: 'KeyF', shiftKey: 'F', key: 'f' },
	KeyG: { keyCode: 71, code: 'KeyG', shiftKey: 'G', key: 'g' },
	KeyH: { keyCode: 72, code: 'KeyH', shiftKey: 'H', key: 'h' },
	KeyI: { keyCode: 73, code: 'KeyI', shiftKey: 'I', key: 'i' },
	KeyJ: { keyCode: 74, code: 'KeyJ', shiftKey: 'J', key: 'j' },
	KeyK: { keyCode: 75, code: 'KeyK', shiftKey: 'K', key: 'k' },
	KeyL: { keyCode: 76, code: 'KeyL', shiftKey: 'L', key: 'l' },
	KeyM: { keyCode: 77, code: 'KeyM', shiftKey: 'M', key: 'm' },
	KeyN: { keyCode: 78, code: 'KeyN', shiftKey: 'N', key: 'n' },
	KeyO: { keyCode: 79, code: 'KeyO', shiftKey: 'O', key: 'o' },
	KeyP: { keyCode: 80, code: 'KeyP', shiftKey: 'P', key: 'p' },
	KeyQ: { keyCode: 81, code: 'KeyQ', shiftKey: 'Q', key: 'q' },
	KeyR: { keyCode: 82, code: 'KeyR', shiftKey: 'R', key: 'r' },
	KeyS: { keyCode: 83, code: 'KeyS', shiftKey: 'S', key: 's' },
	KeyT: { keyCode: 84, code: 'KeyT', shiftKey: 'T', key: 't' },
	KeyU: { keyCode: 85, code: 'KeyU', shiftKey: 'U', key: 'u' },
	KeyV: { keyCode: 86, code: 'KeyV', shiftKey: 'V', key: 'v' },
	KeyW: { keyCode: 87, code: 'KeyW', shiftKey: 'W', key: 'w' },
	KeyX: { keyCode: 88, code: 'KeyX', shiftKey: 'X', key: 'x' },
	KeyY: { keyCode: 89, code: 'KeyY', shiftKey: 'Y', key: 'y' },
	KeyZ: { keyCode: 90, code: 'KeyZ', shiftKey: 'Z', key: 'z' },
	Semicolon: { keyCode: 186, code: 'Semicolon', shiftKey: ':', key: ';' },
	Equal: { keyCode: 187, code: 'Equal', shiftKey: '+', key: '=' },
	NumpadEqual: { keyCode: 187, code: 'NumpadEqual', key: '=', location: 3 },
	Comma: { keyCode: 188, code: 'Comma', shiftKey: '<', key: ',' },
	Minus: { keyCode: 189, code: 'Minus', shiftKey: '_', key: '-' },
	Period: { keyCode: 190, code: 'Period', shiftKey: '>', key: '.' },
	Slash: { keyCode: 191, code: 'Slash', shiftKey: '?', key: '/' },
	Backquote: { keyCode: 192, code: 'Backquote', shiftKey: '~', key: '`' },
	BracketLeft: { keyCode: 219, code: 'BracketLeft', shiftKey: '{', key: '[' },
	Backslash: { keyCode: 220, code: 'Backslash', shiftKey: '|', key: '\\' },
	BracketRight: { keyCode: 221, code: 'BracketRight', shiftKey: '}', key: ']' },
	Quote: { keyCode: 222, code: 'Quote', shiftKey: '"', key: "'" },
}
