name: Publish canary
on:
  pull_request:
    branches: [canary]
    types: [closed]
jobs:
  release:
    name: Release canary
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          node-version: '14.x'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Configure CI Git User
        run: |
          git config --global user.email services@flood.io
          git config --global user.name FloodBot
      - name: Install dependencies
        run: yarn install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: Build all
        run: yarn build
      - name: Publish canary to npm
        run: yarn lerna publish prerelease --yes --dist-tag canary --preid canary --include-merged-tags --exact --force-publish --ignore-changes '**/*.md' 'packages/docs/**'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
